version: "3.9"

services:
  web:
    build: .
    command: ["gunicorn", "yandex_dzen.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db  # добавлено зависимость от PostgreSQL

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: ["celery", "-A", "yandex_dzen.celery.app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db  # добавлена зависимость от PostgreSQL

  celery-beat:
    build: .
    command: ["celery", "-A", "yandex_dzen.celery.app", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - db  # добавлена зависимость от PostgreSQL

  db:
    image: "postgres:alpine"  # контейнер для PostgreSQL
    environment:
      POSTGRES_DB: yandex_dzen_db  # имя базы данных
      POSTGRES_USER: user  # пользователь базы данных
      POSTGRES_PASSWORD: password  # пароль
    ports:
      - "5432:5432"
